name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer Dependencies
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.LARAVEL_NOVA_USERNAME }} ${{ secrets.LARAVEL_NOVA4_TOKEN }}
          composer config github-oauth.github.com ${{ secrets.GH_TOKEN }}
          composer install

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
